name: Cloud Conversations - with Kat Traxler
description: A blog containing cloud research focusing in GCP, AWS and identity architecture
meta_description: "A blog containing cloud research focusing in GCP, AWS and identity architecture"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: "https://kattraxler.cloud/about/"
twitter_username: nightmareJS
plugins: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions

# Details for the RSS feed generator
url: "https://kattraxler.cloud/"
author: "Kat Traxler"

# Disqus config
disqus-shortname: ""

whitelist:
  - jekyll-sitemap

jekyll-mentions:
  base_url: https://twitter.com