name: Kat Traxler - Taste the IAM
description: A Blog about GCP, mostly
meta_description: "A Blog about GCP, mostly"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://kattraxler.github.io/about/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Kat Traxler"

# Disqus config
disqus-shortname: ""
