name: Kat Traxler - Taste the IAM
description: A Blog about GCP, mostly
meta_description: "A Blog about GCP, mostly"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://kattraxler.github.io/about/"
twitter_username: nightmareJS
plugins: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji

# Details for the RSS feed generator
url: "https://kattraxler.github.io/"
author: "Kat Traxler"

# Disqus config
disqus-shortname: ""

whitelist:
  - jekyll-sitemap